name: DMCPhotography
favicon: null
layout_spectrum: 0.87078
typography_spectrum: 0.4147
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c110d'
    - '#5c3100'
    - '#a56d20'
    - '#e8a453'
  brandStrength: 0.6392844307702035
  lightness: 0.3243184396997094
  saturation: 0.49063605070114136
  rhythmicContrast: 0.25
purpose: []
